#!/usr/bin/env bash
#
# Show the message of the day
#
# Copyright (c) 2019 Sergey Briskin
#
for x in /etc/update-motd.d/*
do
    if [ "$1" = "-a" ]; then
        if [ -r "$x" ]; then
            bash $x
        fi
    else
        if [ -x "$x" ]; then
            bash $x
        fi
    fi
done

if [ -r "/etc/motd" ]; then
    cat "/etc/motd"
fi
